aws.disabled = true
elixir.disabled = true
gcloud.disabled = true
nodejs.disabled = true
pulumi.disabled = true
package.disabled = true
docker_context.disabled = true
dotnet.disabled = true

[git_branch]
symbol = " "

# [gcloud]
# format = 'on [$symbol$project]($style) '
# symbol = " "